#!/usr/bin/env bash

# Fail on error and print activity
set -ex

# Make links into the system root for all our stuff
( set +x; cd root; find -type f | {
    while read x; do
      mkdir -p $(dirname "/$x")
      ln -f `pwd`/"$x" "/$x"
    done
  }
)

# Fix some permissions
chown root /etc/sudoers.d/dance
# Ensure directories exist
mkdir -p /var/dance/{tmp,today}
# Ensure bleep queue system exists
touch /var/dance/{new,queue,queue.lock}
chgrp dance /var/dance/{new,queue,queue.lock}

# Ensure list of today's registered students exists
if [ ! -f /var/dance/today/registered-students ]; then
  touch /var/dance/today/registered-students
fi

# Enable system services
systemctl restart opensmtpd
systemctl enable dance-upgrade
systemctl enable dance-buttons
systemctl enable dance-scan
systemctl enable dance-boot
systemctl restart dance-buttons

# Set correct Git origin
git remote add upgrade https://github.com/lessrest/danceschool || true

# Run the hourly script once now
source /etc/cron.hourly/dance-hourly
